### ISSUE TITLE
I get the following error when installing with zgen

### ISSUE THREAD

**Issue by jparsert** [sei40kr/zsh-fast-alias-tips#10]
__fast_alias_tips_preexec:6: no such file or directory: $HOME/.zgen/sei40kr/zsh-fast-alias-tips-master/build/def-matcher

**Comment by sei40kr** [comment]
You must manually build `def-matcher`.

```sh
cd $HOME/.zgen/sei40kr/zsh-fast-alias-tips-master
make
```

I'm using zplugin feature to run `make` after every plugin update.
I think most plugin managers have similar features.
